"use strict";
"require baseclass";
"require ui";
"require dom";
// WARN: generated by rsbuild - do not edit

// The require scope
var __webpack_require__ = {};

// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, getters, values) => {
	var define = (defs, kind) => {
		for(var key in defs) {
			if(__webpack_require__.o(defs, key) && !__webpack_require__.o(exports, key)) {
				Object.defineProperty(exports, key, { enumerable: true, [kind]: defs[key] });
			}
		}
	};
	define(getters, "get");
	define(values, "value");
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  main: () => (/* binding */ main)
});

;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts
const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_e(e, t) {
    let { children: n, ...r } = null === t || "object" != typeof t || Array.isArray(t) ? {} : t, o = function e(t, n = []) {
        for (let r of t)null != r && "boolean" != typeof r && (Array.isArray(r) ? e(r, n) : n.push(r instanceof Node ? r : String(r)));
        return n;
    }(null == n ? [] : Array.isArray(n) ? n : [
        n
    ]);
    if (e === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...o), e;
    }
    if ("function" == typeof e) {
        let t = Reflect.apply(e, void 0, [
            {
                ...r,
                children: o
            }
        ]);
        if (!(t instanceof Node)) throw TypeError("JSX components must return a DOM Node");
        return t;
    }
    if ("string" != typeof e) throw TypeError("JSX element types must be tag names or component functions");
    let f = {}, l = {
        ...r
    };
    for (let [e, t] of Object.entries(l))e.startsWith("on") && "function" == typeof t ? (f[e] = t, delete l[e]) : "boolean" == typeof t && (t ? l[e] = e : delete l[e]);
    let s = Object.keys(l).length > 0 ? o.length > 1 ? E(e, l, o) : E(e, l, o[0]) : o.length > 1 ? E(e, {}, o) : E(e, {}, o[0]);
    for (let [e, t] of Object.entries(f)){
        let n = e.slice(2).toLowerCase();
        s.addEventListener(n, t);
    }
    return s;
}
function jsx(t, n) {
    return jsx_factory_e(t, n);
}
function jsxs(t, n) {
    return jsx_factory_e(t, n);
}
function jsxDEV(t, n) {
    return jsx_factory_e(t, n);
}

;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_cfc1ec583b455be203cca2d0660c10a7/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./web/resources/utils/update.ts
let update_t = L.rpc;
const callGetVersion = update_t.declare({
    object: "luci.fluent",
    method: "get_version"
});
const callStartDownload = update_t.declare({
    object: "luci.fluent",
    method: "start_download",
    params: [
        "url",
        "i18n_url",
        "i18n_urls"
    ]
});
const callCheckDownload = update_t.declare({
    object: "luci.fluent",
    method: "check_download"
});
const callDoInstall = update_t.declare({
    object: "luci.fluent",
    method: "do_install",
    params: [
        "hash",
        "i18n_hash",
        "i18n_hashes"
    ]
});
class GitHubAPIError extends Error {
    status;
    constructor(t, e){
        super(t), this.name = "GitHubAPIError", this.status = e;
    }
}
function matchI18nAsset(t, e, l) {
    let s = e.toLowerCase().trim();
    for (let e of t){
        let t = String(e.name || "").toLowerCase();
        if ("apk" === l) {
            if (t.startsWith(`luci-i18n-fluent-${s}-`) && t.endsWith(".apk")) return e;
        } else if ((t.startsWith(`luci-i18n-fluent-${s}_`) || t.startsWith(`luci-i18n-fluent-${s}-`)) && t.endsWith(".ipk")) return e;
    }
    return null;
}
async function fetchLatestRelease(t, e, l = [], s) {
    let a = {};
    s && (a.Authorization = `token ${s}`);
    let r = await fetch("nightly" === t ? "https://api.github.com/repos/LazuliKao/luci-theme-fluent/releases/tags/nightly" : "https://api.github.com/repos/LazuliKao/luci-theme-fluent/releases/latest", {
        headers: a
    }), i = await r.json();
    if (!r.ok) {
        let t = i?.message ? `: ${i.message}` : "";
        throw new GitHubAPIError(`GitHub API returned status ${r.status}${t}`, r.status);
    }
    let n = i.assets || [], o = null, u = [];
    for (let t of n){
        let l = String(t.name || "");
        "apk" === e && l.startsWith("luci-theme-fluent") && l.endsWith(".apk") ? o = t : "ipk" === e && l.startsWith("luci-theme-fluent") && (l.endsWith("_all.ipk") || l.endsWith(".ipk")) && (o = t);
    }
    for (let t of l){
        let l = matchI18nAsset(n, t, e);
        l && !u.includes(l) && u.push(l);
    }
    return {
        tag_name: String(i.tag_name || ""),
        published_at: String(i.published_at || ""),
        body: String(i.body || ""),
        html_url: String(i.html_url || ""),
        package_asset: o,
        i18n_assets: u
    };
}

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/about.tsx

let about_l = L.form, about_n = "https://ghfast.top/";

let about_u = about_l.DummyValue.extend({
    renderWidget: (l, u, p)=>{
        let h = "1.0.1", b = "ipk", f = [], g = jsxs("div", {
            class: "fluent-about-logo",
            children: [
                jsx("img", {
                    src: `${L.media()}/img/fluent.svg`,
                    alt: "Fluent Theme Logo"
                }),
                jsx("h2", {
                    children: "Fluent Theme"
                }),
                jsx("p", {
                    class: "fluent-about-subtitle",
                    children: _("Fluent Design 2 theme for LuCI")
                })
            ]
        }), y = jsxs("div", {
            class: "fluent-about-details",
            children: [
                jsxs("div", {
                    class: "fluent-about-detail-row",
                    children: [
                        jsxs("strong", {
                            children: [
                                _("Author"),
                                ":"
                            ]
                        }),
                        jsx("span", {
                            children: "LazuliKao"
                        })
                    ]
                }),
                jsxs("div", {
                    class: "fluent-about-detail-row",
                    children: [
                        jsxs("strong", {
                            children: [
                                _("Installed version"),
                                ":"
                            ]
                        }),
                        jsx("span", {
                            class: "fluent-about-current-version",
                            children: "v..."
                        })
                    ]
                }),
                jsxs("div", {
                    class: "fluent-about-detail-row",
                    children: [
                        jsxs("strong", {
                            children: [
                                _("Package format"),
                                ":"
                            ]
                        }),
                        jsx("span", {
                            class: "fluent-about-pkg-type",
                            children: "..."
                        })
                    ]
                }),
                jsxs("div", {
                    class: "fluent-about-detail-row",
                    children: [
                        jsxs("strong", {
                            children: [
                                _("Source code"),
                                ":"
                            ]
                        }),
                        jsx("span", {
                            children: jsx("a", {
                                href: "https://github.com/LazuliKao/luci-theme-fluent",
                                target: "_blank",
                                rel: "noreferrer",
                                children: "GitHub Repository"
                            })
                        })
                    ]
                })
            ]
        }), m = jsxs("select", {
            class: "cbi-input-select",
            id: "update-channel-select",
            children: [
                jsx("option", {
                    value: "stable",
                    children: _("Stable Channel")
                }),
                jsx("option", {
                    value: "nightly",
                    children: _("Nightly Channel (Prerelease)")
                })
            ]
        }), w = jsxs("select", {
            class: "cbi-input-select",
            id: "update-method-select",
            children: [
                jsx("option", {
                    value: "backend_official",
                    children: _("Backend (Official GitHub)")
                }),
                jsx("option", {
                    value: "backend_ghproxy",
                    children: _("Backend (GHProxy Acceleration)")
                })
            ]
        }), v = jsx("button", {
            class: "btn cbi-button cbi-button-action",
            type: "button",
            children: _("Check for updates")
        }), k = jsxs("div", {
            class: "fluent-update-controls",
            style: "display: flex; gap: 15px; align-items: center; flex-wrap: wrap;",
            children: [
                jsxs("div", {
                    class: "fluent-update-channel-selector",
                    children: [
                        jsxs("label", {
                            htmlFor: "update-channel-select",
                            children: [
                                _("Update channel"),
                                ": "
                            ]
                        }),
                        m
                    ]
                }),
                v
            ]
        }), x = jsx("div", {
            class: "fluent-update-status",
            style: "display: none"
        }), T = jsx("div", {
            class: "fluent-progress-bar__fill",
            style: "width: 0%"
        }), C = jsx("div", {
            class: "fluent-progress-bar",
            style: "display: none",
            children: T
        }), S = jsx("div", {
            class: "fluent-progress-text",
            style: "display: none"
        }), $ = jsx("div", {
            class: "fluent-update-card",
            style: "display: none"
        }), F = jsxs("div", {
            class: "fluent-about-manager",
            children: [
                g,
                y,
                jsx("hr", {
                    class: "fluent-about-divider"
                }),
                jsx("h3", {
                    children: _("Software Update")
                }),
                k,
                x,
                $,
                C,
                S
            ]
        }), P = (e, t = "info")=>{
            dom.content(x, [
                document.createTextNode(e)
            ]), x.className = `fluent-update-status status-${t}`, x.style.display = "block";
        }, A = (e, t, a)=>{
            C.style.display = "block", S.style.display = "block", T.style.width = `${t}%`, T.className = `fluent-progress-bar__fill fill-${e}`, dom.content(S, [
                document.createTextNode(`${a} (${t}%)`)
            ]);
        }, z = ()=>{
            C.style.display = "none", S.style.display = "none";
        };
        (async ()=>{
            try {
                let e = await callGetVersion();
                h = e.version, b = e.pkg_type, f = e.installed_i18n || (e.i18n_zh_cn_installed ? [
                    "zh-cn"
                ] : []);
                let t = y.querySelector(".fluent-about-current-version");
                t && (t.textContent = `v${h}`);
                let a = y.querySelector(".fluent-about-pkg-type");
                a && (a.textContent = "apk" === b ? "APK (OpenWrt 25.12+)" : "IPK (OpenWrt 24.10)");
            } catch (e) {
                console.error("Failed to fetch version", e), P(_("Failed to fetch current theme version."), "error");
            }
        })();
        let N = async (l)=>{
            let s = m.value;
            try {
                let c = await fetchLatestRelease(s, b, f, l);
                console.log(c), v.disabled = !1;
                let u = h.replace(/^v/, "").trim(), p = c.tag_name.replace(/^v/, "").trim(), g = L.naturalCompare(p, u) > 0, y = !g && "nightly" !== s;
                if (y ? P(_("Your theme is up to date!"), "success") : P(g ? _("A new version is available!") : _("Nightly build available (reinstallation check)."), g ? "warn" : "info"), !c.package_asset) return void P(_("No matching package asset found for your system architecture in this release."), "error");
                let k = c.body ? c.body : "", x = jsx("button", {
                    class: "btn cbi-button cbi-button-save",
                    type: "button",
                    style: "white-space: nowrap;",
                    children: _("Download and Install")
                }), T = [
                    jsxs("div", {
                        class: "fluent-update-header",
                        children: [
                            jsx("span", {
                                class: "fluent-update-badge",
                                children: "nightly" === p ? "Nightly" : `v${p}`
                            }),
                            jsx("span", {
                                class: "fluent-update-date",
                                children: c.published_at.split("T")[0]
                            })
                        ]
                    })
                ];
                k && T.push(jsx("pre", {
                    class: "fluent-update-changelog",
                    children: k
                })), y || T.push(jsxs("div", {
                    class: "fluent-update-footer",
                    style: "display: flex; align-items: center; justify-content: flex-end; gap: 10px; margin-top: 15px; flex-wrap: wrap;",
                    children: [
                        w,
                        x
                    ]
                })), dom.content($, T), $.style.display = "block", x.addEventListener("click", async ()=>{
                    let l = c.package_asset;
                    if (!l) return void P(_("No matching package asset found for your system architecture in this release."), "error");
                    x.disabled = !0, m.disabled = !0, w.disabled = !0, v.disabled = !0, P(_("Starting update process..."), "info");
                    let s = c.i18n_assets || [], d = null, u = [];
                    for (let e of (l.digest?.startsWith("sha256:") ? d = l.digest.replace("sha256:", "") : (console.warn("Unable to determine expected package hash from digest. Skipping verification."), d = "skip"), s))e.digest?.startsWith("sha256:") ? u.push(e.digest.replace("sha256:", "")) : u.push("skip");
                    let p = async ()=>{
                        let c = w.value.includes("ghproxy");
                        P(_("Starting backend download..."), "info"), A("download", 0, _("Downloading on router"));
                        let p = c ? about_n + l.browser_download_url : l.browser_download_url, h = s.map((e)=>c ? about_n + e.browser_download_url : e.browser_download_url).join(" "), b = await callStartDownload(p, h.split(" ")[0] || "", h);
                        if (0 !== b.result) throw Error(b.message || "Failed to start router download.");
                        for(;;){
                            let e = await callCheckDownload(), t = e.size || 0, a = s.reduce((e, t)=>e + (t.size || 0), 0), n = l.size + a, i = n > 0 ? Math.min(Math.round(t / n * 100), 100) : 0;
                            if (A("download", i, `${_("Downloading on router")} (${(t / 1024).toFixed(0)} / ${(n / 1024).toFixed(0)} KB)`), !e.running) if (0 !== e.code) throw Error("Router background download failed or file is empty.");
                            else break;
                            await new Promise((e)=>setTimeout(e, 1000));
                        }
                        if (!await new Promise((l)=>{
                            L.ui.showModal(_("Confirm Installation"), jsxs(Fragment, {
                                children: [
                                    jsx("div", {
                                        children: jsx("p", {
                                            children: _("The theme package is ready. Are you sure you want to proceed with the installation?")
                                        })
                                    }),
                                    jsxs("div", {
                                        class: "right",
                                        children: [
                                            jsx("button", {
                                                type: "button",
                                                class: "btn",
                                                onclick: ()=>{
                                                    L.ui.hideModal(), l(!1);
                                                },
                                                children: _("Cancel")
                                            }),
                                            jsx("button", {
                                                type: "button",
                                                class: "btn cbi-button-action",
                                                onclick: ()=>{
                                                    L.ui.hideModal(), l(!0);
                                                },
                                                children: _("Continue")
                                            })
                                        ]
                                    })
                                ]
                            }));
                        })) throw Error(_("Installation cancelled by user."));
                        P(_("Triggering installation on router..."), "info"), A("install", 100, _("Installing package"));
                        let f = await callDoInstall(d, u[0] || "", u.join(" "));
                        if (0 !== f.result) throw Error(f.message || "Router installation failed.");
                        let g = jsx("pre", {
                            style: "background: var(--fluent-code-bg, #1a1a1a); color: var(--fluent-text, #fff); padding: 10px; border-radius: 4px; font-family: monospace; font-size: 12px; white-space: pre-wrap; word-wrap: break-word; max-height: 200px; overflow-y: auto; margin-top: 15px;"
                        });
                        (async ()=>{
                            let e = L.env.ubuspath || "/ubus", t = L.env.sessionid;
                            for(;;)try {
                                let a = await fetch(e, {
                                    method: "POST",
                                    headers: {
                                        "Content-Type": "application/json"
                                    },
                                    body: JSON.stringify({
                                        jsonrpc: "2.0",
                                        id: 1,
                                        method: "call",
                                        params: [
                                            t,
                                            "luci.fluent",
                                            "get_install_log",
                                            {}
                                        ]
                                    })
                                }), l = await a.json();
                                if (l.error) break;
                                l.result?.[1]?.log && (g.textContent = l.result[1].log, g.scrollTop = g.scrollHeight), await new Promise((e)=>setTimeout(e, 1000));
                            } catch  {
                                break;
                            }
                        })(), P(_("Theme successfully updated! Reloading RPC service, please refresh the page in 5 seconds."), "success"), A("done", 100, _("Finished")), dom.content($, [
                            jsxs("div", {
                                class: "fluent-update-success",
                                children: [
                                    jsx("h3", {
                                        style: "color: var(--fluent-success); text-align: center;",
                                        children: _("Upgrade Successful!")
                                    }),
                                    jsx("p", {
                                        style: "text-align: center; margin: 15px 0;",
                                        children: _("The theme is being installed on your router. The logs are displayed below. Reloading the web interface will apply the changes once RPCD restarts.")
                                    }),
                                    g,
                                    jsx("div", {
                                        style: "display: flex; justify-content: center; margin-top: 20px;",
                                        children: jsx("button", {
                                            class: "btn cbi-button-action",
                                            type: "button",
                                            style: "margin-top: 15px",
                                            onclick: ()=>{
                                                window.location.reload();
                                            },
                                            children: _("Reload Web Interface")
                                        })
                                    })
                                ]
                            })
                        ]);
                    };
                    try {
                        await p();
                    } catch (e) {
                        console.error("Update failed", e), P(`${_("Update failed")}: ${e instanceof Error ? e.message : String(e)}`, "error"), x.disabled = !1, x.removeAttribute("disabled"), m.disabled = !1, m.removeAttribute("disabled"), w.disabled = !1, w.removeAttribute("disabled"), v.disabled = !1, v.removeAttribute("disabled"), z();
                    }
                });
            } catch (l) {
                if (v.disabled = !1, console.error("Failed checking updates", l), l instanceof GitHubAPIError && 403 === l.status) {
                    let n = jsx("input", {
                        type: "text",
                        class: "cbi-input-text",
                        style: "width: 100%",
                        placeholder: "ghp_..."
                    }), r = jsx("p", {
                        children: _("API rate limit exceeded. Please enter a GitHub Token to continue. This token is only used for frontend requests and will not be saved on the router backend.")
                    }), i = jsxs("p", {
                        style: "margin-top: 10px; font-size: 13px; color: var(--fluent-text-secondary);",
                        children: [
                            _("You can create a new token at"),
                            " ",
                            jsx("a", {
                                href: "https://github.com/settings/personal-access-tokens",
                                target: "_blank",
                                rel: "noopener noreferrer",
                                children: "https://github.com/settings/personal-access-tokens/new"
                            }),
                            ".",
                            _("The token does NOT require any permissions/scopes to be granted (read-only public access is sufficient).")
                        ]
                    }), s = jsx("pre", {
                        style: "margin-top: 10px; margin-bottom: 15px; font-size: 12px; white-space: pre-wrap; word-break: break-word; color: var(--fluent-error-text); background: var(--fluent-card-bg); padding: 8px; border-radius: var(--fluent-border-radius);",
                        children: l instanceof Error ? l.message : String(l)
                    });
                    L.ui.showModal(_("GitHub Token Required"), jsxs(Fragment, {
                        children: [
                            r,
                            i,
                            s,
                            n,
                            jsxs("div", {
                                class: "right",
                                children: [
                                    jsx("button", {
                                        type: "button",
                                        class: "btn",
                                        onclick: ()=>L.ui.hideModal(),
                                        children: _("Cancel")
                                    }),
                                    jsx("button", {
                                        type: "button",
                                        class: "btn cbi-button-save",
                                        onclick: ()=>{
                                            let e = n.value.trim();
                                            L.ui.hideModal(), e && (P(_("Retrying with token..."), "info"), v.disabled = !0, N(e));
                                        },
                                        children: _("Submit")
                                    })
                                ]
                            })
                        ]
                    }));
                } else P(`${_("Failed to check for updates")}: ${l instanceof Error ? l.message : String(l)}`, "error");
            }
        };
        return v.addEventListener("click", ()=>{
            P(_("Checking for updates..."), "info"), v.disabled = !0, $.style.display = "none", z(), N();
        }), F;
    }
});
const registerAboutTab = (e)=>{
    e.tab("about", _("About")), e.taboption("about", about_u, "_about_mgr");
};

;// CONCATENATED MODULE: ./web/resources/fluent-defaults.ts
const FLUENT_DEFAULTS = {
    mode: "auto",
    primary: "#0078d4",
    dark_primary: "#4da6ff",
    progressbar_font: "#2e2b60",
    dark_progressbar_font: "#d6d9e5",
    page_bg: "#fafafa",
    card_bg: "#ffffff",
    sidebar_bg: "#f3f3f3",
    dark_page_bg: "#1b1b1b",
    dark_card_bg: "#2d2d2d",
    dark_sidebar_bg: "#1f1f1f",
    font_weight: "normal",
    font_size: "14",
    border_radius: "4",
    control_height: "32",
    sidebar_width: "260",
    header_height: "48",
    login_bg: "microsoft",
    blur: "40",
    transparency: "0.8",
    blur_dark: "20",
    transparency_dark: "0.8",
    card_shadow: "small",
    transition_speed: "normal",
    custom_css: "",
    custom_select: "1",
    view_transition: "1",
    tab_animation: "1",
    prefers_reduced_motion: "1",
    loading_bar: "1",
    direction_mode: "auto",
    progressbar_text_position: "top-start"
};
const fluentFlagDefault = (r)=>"1" === r;

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/advanced.ts
let advanced_e = L.form;

const registerAdvancedTab = (t)=>{
    t.tab("advanced", _("Advanced"), _("Adjust layout, typography, transition timing, shadows, and inject custom CSS variables or rules when the built-in controls are not enough."));
    {
        let d = t.taboption("advanced", advanced_e.Value, "font_size", _("Base font size"), _("Sets the base interface font size in pixels. Most theme text scales from this value through the Fluent CSS variables. Recommended range: 12-18px."));
        d.datatype = "range(12,18)", d.default = FLUENT_DEFAULTS.font_size, d.rmempty = !1, d.placeholder = FLUENT_DEFAULTS.font_size;
    }
    {
        let d = t.taboption("advanced", advanced_e.Value, "sidebar_width", _("Sidebar width"), _("Width of the main navigation sidebar in pixels."));
        d.datatype = "range(200,420)", d.default = FLUENT_DEFAULTS.sidebar_width, d.rmempty = !1, d.placeholder = FLUENT_DEFAULTS.sidebar_width;
    }
    {
        let d = t.taboption("advanced", advanced_e.Value, "header_height", _("Header height"), _("Height of the top header bar in pixels."));
        d.datatype = "range(40,96)", d.default = FLUENT_DEFAULTS.header_height, d.rmempty = !1, d.placeholder = FLUENT_DEFAULTS.header_height;
    }
    {
        let d = t.taboption("advanced", advanced_e.ListValue, "border_radius", _("Corner radius"), _("Controls the shared Fluent corner radius tokens used by cards, buttons, inputs, and related UI surfaces."));
        d.value("0", _("Square (0px)")), d.value("2", _("Small (2px)")), d.value("4", _("Medium (4px)")), d.value("6", _("Rounded (6px)")), d.value("8", _("Large (8px)")), d.value("12", _("Extra large (12px)")), d.default = FLUENT_DEFAULTS.border_radius, d.rmempty = !1;
    }
    {
        let d = t.taboption("advanced", advanced_e.ListValue, "card_shadow", _("Card shadow"), _("Select the shadow depth applied to themed cards and panels."));
        d.value("none", _("None")), d.value("small", _("Small")), d.value("medium", _("Medium")), d.value("large", _("Large")), d.default = FLUENT_DEFAULTS.card_shadow, d.rmempty = !1;
    }
    {
        let d = t.taboption("advanced", advanced_e.ListValue, "transition_speed", _("Theme transition speed"), _("Controls the shared Fluent transition timing used by menu, header, and other theme animations."));
        d.value("fast", _("Fast")), d.value("normal", _("Normal")), d.value("slow", _("Slow")), d.value("none", _("Disabled")), d.default = FLUENT_DEFAULTS.transition_speed, d.rmempty = !1;
    }
    {
        let d = t.taboption("advanced", advanced_e.TextValue, "custom_css", _("Custom CSS"), _("Optional raw CSS injected into the Fluent header template. Use this for extra --fluent-* variable overrides or page-specific tweaks that are not exposed as dedicated options."));
        d.default = FLUENT_DEFAULTS.custom_css, d.rmempty = !0, d.rows = 12, d.wrap = "off", d.placeholder = ":root {\n  --fluent-sidebar-width: 280px;\n  --fluent-card-shadow: none;\n}";
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/animation.ts
let animation_e = L.form;

const registerAnimationTab = (n)=>{
    n.tab("animation", _("Animation"));
    {
        let i = n.taboption("animation", animation_e.Flag, "view_transition", _("Enable page transition animation"), _("Use the browser View Transition API to animate navigation between LuCI pages when supported."));
        i.default = fluentFlagDefault(FLUENT_DEFAULTS.view_transition) ? i.enabled : i.disabled, i.rmempty = !1;
    }
    {
        let i = n.taboption("animation", animation_e.Flag, "tab_animation", _("Enable tab underline animation"), _("Animate the active underline when switching between native LuCI tabs and themed tab menus."));
        i.default = fluentFlagDefault(FLUENT_DEFAULTS.tab_animation) ? i.enabled : i.disabled, i.rmempty = !1;
    }
    {
        let i = n.taboption("animation", animation_e.Flag, "prefers_reduced_motion", _("Respect reduced-motion preference"), _("When enabled, Fluent animations follow the browser or operating system reduced-motion preference."));
        i.default = fluentFlagDefault(FLUENT_DEFAULTS.prefers_reduced_motion) ? i.enabled : i.disabled, i.rmempty = !1, i.depends("tab_animation", "1");
    }
    {
        let i = n.taboption("animation", animation_e.Flag, "loading_bar", _("Show top loading bar"), _("Display the themed loading indicator at the top edge during page loads and transitions."));
        i.default = fluentFlagDefault(FLUENT_DEFAULTS.loading_bar) ? i.enabled : i.disabled, i.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/shared.ts
let shared_e = L.form;
const transparencySteps = [
    0,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1
];
let shared_t = "fluent-live-preview", shared_r = /(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i, shared_a = {
    primary: {
        cssVar: "--fluent-primary",
        isDark: !1
    },
    dark_primary: {
        cssVar: "--fluent-primary",
        isDark: !0
    },
    page_bg: {
        cssVar: "--fluent-bg",
        isDark: !1
    },
    dark_page_bg: {
        cssVar: "--fluent-bg",
        isDark: !0
    },
    card_bg: {
        cssVar: "--fluent-bg-card",
        isDark: !1
    },
    dark_card_bg: {
        cssVar: "--fluent-bg-card",
        isDark: !0
    },
    sidebar_bg: {
        cssVar: "--fluent-sidebar-bg",
        isDark: !1
    },
    dark_sidebar_bg: {
        cssVar: "--fluent-sidebar-bg",
        isDark: !0
    },
    progressbar_font: {
        cssVar: "--fluent-progressbar-font-color",
        isDark: !1
    },
    dark_progressbar_font: {
        cssVar: "--fluent-progressbar-font-color",
        isDark: !0
    }
}, shared_l = new globalThis.Map();
const configureHexColorValue = (s, o, n = !1)=>{
    s.rmempty = !1, s.validate = (e, t)=>!e || shared_r.test(String(t)) || _("Expecting: %s").format(_("valid HEX color value")), s.render = (i, c, d)=>{
        let u = shared_e.Value.prototype.render.call(s, i, c, d), p = ()=>{
            let e = document.querySelector(`[id^="widget.cbid.fluent."][id$=".${o}"]`);
            e && ((e, t)=>{
                if ("true" === e.dataset.fluentColorPicker) return;
                let a = e.parentElement;
                if (!a) return;
                e.dataset.fluentColorPicker = "true", e.classList.add("fluent-color-field__text");
                let l = document.createElement("div");
                l.className = "fluent-color-field";
                let s = document.createElement("label");
                s.className = "fluent-color-swatch", s.title = _("Choose color");
                let o = document.createElement("input");
                o.type = "color", o.className = "fluent-color-swatch__input", o.setAttribute("aria-label", _("Choose color"));
                let n = document.createElement("span");
                n.className = "fluent-color-swatch__preview";
                let i = (e)=>{
                    shared_r.test(e) && (o.value = e, n.style.backgroundColor = e);
                };
                i(e.value), o.addEventListener("input", ()=>{
                    e.value = o.value, n.style.backgroundColor = o.value, shared_r.test(o.value) && t(o.value);
                }), e.addEventListener("input", ()=>{
                    i(e.value), shared_r.test(e.value) && t(e.value);
                }), s.appendChild(o), s.appendChild(n), a.insertBefore(l, e), l.appendChild(e), l.appendChild(s);
            })(e, (e)=>((e, r)=>{
                    let s = shared_a[e];
                    if (!s) return;
                    let o = `${s.isDark ? "dark" : "light"}|${s.cssVar}`;
                    shared_l.set(o, {
                        selector: s.isDark ? ':root[data-theme="dark"]' : ":root",
                        cssVar: s.cssVar,
                        value: r
                    }), (()=>{
                        let e, r = ((e = document.getElementById(shared_t)) || ((e = document.createElement("style")).id = shared_t, document.head.appendChild(e)), e), a = new globalThis.Map();
                        for (let e of shared_l.values()){
                            let t = a.get(e.selector) ?? [];
                            t.push(`${e.cssVar}: ${e.value};`), a.set(e.selector, t);
                        }
                        let s = "";
                        for (let [e, t] of a)s += `${e} { ${t.join(" ")} }\n`;
                        r.textContent = s;
                    })();
                })(o, e));
        };
        return n ? requestAnimationFrame(p) : setTimeout(p, 0), u;
    };
};
const createModeSubtabs = (t, r, a)=>{
    let l = t.taboption(r, shared_e.SectionValue, a, shared_e.TypedSection, "global").subsection;
    return l.anonymous = !0, l.addremove = !1, l.tab("light", _("Light mode")), l.tab("dark", _("Dark mode")), l;
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/colors.ts
let colors_r = L.form;


const registerColorsTab = (t)=>{
    t.tab("colors", _("Colors"));
    let d = createModeSubtabs(t, "colors", "colors_mode_tabs");
    {
        let o = d.taboption("light", colors_r.Value, "primary", _("Accent color"), _("HEX color used as the primary Fluent accent when the interface is rendered in light mode."));
        o.default = FLUENT_DEFAULTS.primary, configureHexColorValue(o, "primary");
    }
    {
        let o = d.taboption("light", colors_r.Value, "progressbar_font", _("Progress bar text color"), _("HEX color used for progress-bar labels while the interface is rendered in light mode."));
        o.default = FLUENT_DEFAULTS.progressbar_font, configureHexColorValue(o, "progressbar_font");
    }
    {
        let o = d.taboption("light", colors_r.Value, "page_bg", _("Page background"), _("HEX color used for the main page background in light mode."));
        o.default = FLUENT_DEFAULTS.page_bg, configureHexColorValue(o, "page_bg");
    }
    {
        let o = d.taboption("light", colors_r.Value, "card_bg", _("Card background"), _("HEX color used for container/card elements in light mode."));
        o.default = FLUENT_DEFAULTS.card_bg, configureHexColorValue(o, "card_bg");
    }
    {
        let o = d.taboption("light", colors_r.Value, "sidebar_bg", _("Sidebar background"), _("HEX color used for the navigation sidebar in light mode."));
        o.default = FLUENT_DEFAULTS.sidebar_bg, configureHexColorValue(o, "sidebar_bg");
    }
    {
        let o = d.taboption("dark", colors_r.Value, "dark_primary", _("Accent color"), _("HEX color used as the primary Fluent accent when the interface is rendered in dark mode."));
        o.default = FLUENT_DEFAULTS.dark_primary, configureHexColorValue(o, "dark_primary", !0);
    }
    {
        let o = d.taboption("dark", colors_r.Value, "dark_progressbar_font", _("Progress bar text color"), _("HEX color used for progress-bar labels while the interface is rendered in dark mode."));
        o.default = FLUENT_DEFAULTS.dark_progressbar_font, configureHexColorValue(o, "dark_progressbar_font", !0);
    }
    {
        let o = d.taboption("dark", colors_r.Value, "dark_page_bg", _("Page background"), _("HEX color used for the main page background in dark mode."));
        o.default = FLUENT_DEFAULTS.dark_page_bg, configureHexColorValue(o, "dark_page_bg", !0);
    }
    {
        let o = d.taboption("dark", colors_r.Value, "dark_card_bg", _("Card background"), _("HEX color used for container/card elements in dark mode."));
        o.default = FLUENT_DEFAULTS.dark_card_bg, configureHexColorValue(o, "dark_card_bg", !0);
    }
    {
        let o = d.taboption("dark", colors_r.Value, "dark_sidebar_bg", _("Sidebar background"), _("HEX color used for the navigation sidebar in dark mode."));
        o.default = FLUENT_DEFAULTS.dark_sidebar_bg, configureHexColorValue(o, "dark_sidebar_bg", !0);
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/general.ts
let general_e = L.form;

const registerGeneralTab = (a)=>{
    a.tab("general", _("General"));
    {
        let o = a.taboption("general", general_e.ListValue, "mode", _("Color mode"));
        o.value("auto", _("Follow system")), o.value("light", _("Force light mode")), o.value("dark", _("Force dark mode")), o.default = FLUENT_DEFAULTS.mode, o.rmempty = !1, o.description = _("Use the system/browser preference, or always render the Fluent theme in a fixed light or dark palette.");
    }
    {
        let o = a.taboption("general", general_e.ListValue, "direction_mode", _("Text direction"));
        o.value("auto", _("Automatic (Arabic/Persian locales only)")), o.value("rtl", _("Force RTL")), o.value("ltr", _("Force LTR")), o.default = FLUENT_DEFAULTS.direction_mode, o.rmempty = !1, o.description = _("Choose the document direction for authenticated and login pages. Automatic mode resolves Arabic and Persian locale codes (ar, ar_*, ar-*, fa, fa_*, fa-*) to RTL and falls back to LTR for missing or unrecognized locales.");
    }
    {
        let o = a.taboption("general", general_e.ListValue, "font_weight", _("Navigation font weight"));
        o.value("normal", _("Normal")), o.value("600", _("Semibold")), o.default = FLUENT_DEFAULTS.font_weight, o.rmempty = !1, o.description = _("Controls the font weight used by main navigation labels and related theme text accents.");
    }
    {
        let o = a.taboption("general", general_e.ListValue, "control_height", _("Control height"));
        o.value("32", _("Compact (32px)")), o.value("42", _("Comfortable (42px)")), o.default = FLUENT_DEFAULTS.control_height, o.rmempty = !1, o.description = _("Applies to standard buttons, inputs, selects, and similar form controls across the theme.");
    }
    {
        let r = a.taboption("general", general_e.Flag, "custom_select", _("Use Fluent custom select dropdowns"), _("Replace native select elements with the theme's custom dropdown widget."));
        r.default = fluentFlagDefault(FLUENT_DEFAULTS.custom_select) ? r.enabled : r.disabled, r.rmempty = !1;
    }
    {
        let o = a.taboption("general", general_e.ListValue, "progressbar_text_position", _("Progress bar text position"));
        o.value("top-start", _("Above bar, start")), o.value("bottom-start", _("Below bar, start")), o.value("top-end", _("Above bar, end")), o.value("bottom-end", _("Below bar, end")), o.default = FLUENT_DEFAULTS.progressbar_text_position, o.rmempty = !1, o.description = _("Position of progress-bar labels relative to the bar. Start/end alignment follows the text direction (LTR or RTL).");
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/login.tsx

let login_a = L.form, login_n = L.rpc, login_l = L.fs, login_i = L.ui, login_r = login_n.declare({
    object: "luci.fluent",
    method: "avail",
    expect: {
        avail: 0
    }
}), login_o = login_n.declare({
    object: "luci.fluent",
    method: "remove",
    params: [
        "filename"
    ],
    expect: {
        result: 0
    }
}), login_d = login_n.declare({
    object: "luci.fluent",
    method: "rename",
    params: [
        "newname"
    ],
    expect: {
        result: 0
    }
});


let login_g = new Set([
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "mp4",
    "webm"
]), login_p = (e)=>e.split(".").pop()?.toLowerCase() ?? "", login_m = (e)=>login_g.has(login_p(e)), login_b = (e)=>e >= 1048576 ? `${(e / 1024 / 1024).toFixed(1)} GiB` : e >= 1024 ? `${(e / 1024).toFixed(1)} MiB` : `${e} KiB`, login_f = (e, t)=>{
    if (0 !== e) throw Error(`${t} failed with code ${e}.`);
}, login_h = (e, t)=>{
    dom.content(e, t);
}, login_v = login_a.DummyValue.extend({
    renderWidget: (a, n, c)=>{
        let s = jsx("div", {
            class: "cbi-value-description fluent-bg-status",
            children: "Ready to upload or remove custom backgrounds."
        }), u = jsx("div", {
            class: "fluent-bg-hint",
            children: "Supported formats: JPG, PNG, GIF, WEBP, MP4, WEBM."
        }), g = jsx("button", {
            class: "btn cbi-button cbi-button-action",
            type: "button",
            children: "Upload background"
        }), v = jsx("div", {
            class: "fluent-bg-actions",
            children: g
        }), y = jsx("div", {
            class: "fluent-bg-list"
        }), k = (e)=>{
            login_h(s, [
                document.createTextNode(e)
            ]);
        }, $ = ()=>login_l.list("/www/luci-static/fluent/background").catch(()=>[]).then((a)=>{
                let n = a.filter((e)=>"file" === e.type && login_m(String(e.name ?? ""))).sort((e, t)=>String(e.name ?? "").localeCompare(String(t.name ?? "")));
                n.length ? login_h(y, n.map((a)=>{
                    let n, l, r, d = String(a.name ?? ""), c = jsx("button", {
                        class: "btn cbi-button cbi-button-remove",
                        type: "button",
                        children: "Delete"
                    }), s = login_i.createHandlerFn(undefined, ()=>(k(`Deleting ${d}...`), login_o(d).then((e)=>(login_f(e, `Deleting ${d}`), $().then(()=>{
                                k(`Deleted ${d}.`);
                            }))).catch((e)=>{
                            k(`Failed to delete ${d}: ${e instanceof Error ? e.message : String(e)}`);
                        })));
                    return s && c.addEventListener("click", s), jsxs("div", {
                        class: "fluent-bg-item",
                        children: [
                            (n = login_p(d), l = `/luci-static/fluent/background/${encodeURIComponent(d)}`, "mp4" === n || "webm" === n ? jsx("video", {
                                class: "fluent-bg-preview fluent-bg-preview-video",
                                muted: !0,
                                playsInline: !0,
                                preload: "metadata",
                                src: l
                            }) : jsx("div", {
                                class: "fluent-bg-preview",
                                style: `background-image:url('${l.replace(/'/g, "%27")}')`
                            })),
                            jsxs("div", {
                                class: "fluent-bg-meta",
                                children: [
                                    jsx("strong", {
                                        class: "fluent-bg-name",
                                        title: d,
                                        children: d
                                    }),
                                    jsx("span", {
                                        class: "fluent-bg-size",
                                        children: (r = Number(a.size ?? 0)) > 0 ? login_b(Math.max(1, Math.ceil(r / 1024))) : "Unknown size"
                                    })
                                ]
                            }),
                            jsx("div", {
                                class: "fluent-bg-item-actions",
                                children: c
                            })
                        ]
                    });
                })) : login_h(y, jsxs("div", {
                    class: "fluent-bg-empty",
                    children: [
                        jsx("strong", {
                            children: "No custom backgrounds yet"
                        }),
                        jsx("span", {
                            children: "Upload an image or video to use it on the login page."
                        })
                    ]
                }));
            });
        return g.addEventListener("click", ()=>{
            k("Selecting background file..."), login_i.uploadFile("/tmp/fluent_background.tmp").then((e)=>{
                let t;
                if (!e?.name) throw Error("Upload did not return a filename.");
                let a = "" !== (t = e.name.replace(/^.*[\\/]/, "").replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "")) && "." !== t && ".." !== t && login_m(t) ? t : `background-${Date.now()}.jpg`;
                return k(`Saving ${a}...`), login_d(a).then((e)=>(login_f(e, `Saving ${a}`), $().then(()=>{
                        k(`Saved ${a}.`);
                    }))).catch((e)=>{
                    k(`Failed to save ${a}: ${e instanceof Error ? e.message : String(e)}`);
                });
            }).catch((e)=>{
                let t = e instanceof Error ? e.message : String(e);
                t && "false" !== t ? k(`Upload failed: ${t}`) : k("Upload canceled.");
            });
        }), login_r().then((e)=>{
            k(`Ready to upload or remove custom backgrounds. Available space: ${login_b(e)}.`);
        }).catch(()=>{
            k("Ready to upload or remove custom backgrounds.");
        }), $(), jsx("div", {
            class: "fluent-bg-manager",
            children: [
                s,
                u,
                v,
                y
            ]
        });
    }
});
const registerLoginTab = (e)=>{
    e.tab("login", _("Login page"), _("Customize the login page background, card opacity, and blur radius for light and dark modes."));
    {
        let t = e.taboption("login", login_a.ListValue, "login_bg", "Background source", "Select the background image source for the login page.");
        t.value("microsoft", "Microsoft dynamic canvas"), t.value("custom", "Custom background"), t.value("bing", "Bing daily wallpaper"), t.default = FLUENT_DEFAULTS.login_bg, t.rmempty = !1;
    }
    e.taboption("login", login_v, "_bg_mgr", "Custom backgrounds", "Upload and manage custom background images for the login page.").depends("login_bg", "custom");
    let t = createModeSubtabs(e, "login", "login_mode_tabs");
    {
        let e = t.taboption("light", login_a.ListValue, "transparency", _("Login card opacity"), _("Opacity of the login card in light mode. 0 is fully transparent and 1 is fully opaque."));
        for (let t of transparencySteps)e.value(String(t));
        e.default = FLUENT_DEFAULTS.transparency, e.rmempty = !1;
    }
    {
        let e = t.taboption("light", login_a.Value, "blur", _("Backdrop blur radius"), _("Blur radius in pixels behind the login card in light mode. Use 0 to disable blur."));
        e.datatype = "ufloat", e.default = FLUENT_DEFAULTS.blur, e.rmempty = !1;
    }
    {
        let e = t.taboption("dark", login_a.ListValue, "transparency_dark", _("Login card opacity"), _("Opacity of the login card in dark mode. 0 is fully transparent and 1 is fully opaque."));
        for (let t of transparencySteps)e.value(String(t));
        e.default = FLUENT_DEFAULTS.transparency_dark, e.rmempty = !1;
    }
    {
        let e = t.taboption("dark", login_a.Value, "blur_dark", _("Backdrop blur radius"), _("Blur radius in pixels behind the login card in dark mode. Use 0 to disable blur."));
        e.datatype = "ufloat", e.default = FLUENT_DEFAULTS.blur_dark, e.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ./web/resources/menu-layout.ts
let menu_layout_e = "primary:", menu_layout_t = new Set([
    "version",
    "custom",
    "titles",
    "categoryMoves",
    "itemMoves",
    "hiddenCategories",
    "hiddenItems"
]);
function menu_layout_n(e) {
    return "function" == typeof _ ? _(e) : e;
}
function primaryCategoryId(t) {
    return `${menu_layout_e}${t}`;
}
function menu_layout_r(t) {
    return t.startsWith(menu_layout_e) ? t.slice(menu_layout_e.length) : null;
}
function menu_layout_i(e) {
    let t = [], r = [];
    for (let i of ui.menu.getChildren(e))if (i.satisfied) for (let e of ui.menu.getChildren(i)){
        let l = e.title?.trim();
        if (!e.satisfied || !l) continue;
        let o = `${i.name}/${e.name}`, u = menu_layout_n(l);
        for (let a of (t.push({
            path: o,
            pathSegments: [
                i.name,
                e.name
            ],
            node: e,
            title: u,
            rawTitle: l
        }), ui.menu.getChildren(e))){
            let t = a.title?.trim();
            a.satisfied && t && r.push({
                path: `${o}/${a.name}`,
                pathSegments: [
                    i.name,
                    e.name,
                    a.name
                ],
                node: a,
                title: menu_layout_n(t),
                rawTitle: t,
                originalPrimaryPath: o,
                originalPrimaryTitle: u
            });
        }
    }
    return {
        primaries: t,
        items: r
    };
}
function discoverMenuItems(e) {
    return menu_layout_i(e).items;
}
function menu_layout_l(e) {
    let t = e.primaries.map((e)=>({
            id: primaryCategoryId(e.path),
            title: e.title,
            items: []
        })), n = new Map(t.map((e)=>[
            e.id,
            e
        ]));
    for (let t of e.items)n.get(primaryCategoryId(t.originalPrimaryPath))?.items.push(t.path);
    return t;
}
function buildDefaultMenuCategories(e) {
    return menu_layout_l(menu_layout_i(e));
}
function menu_layout_o(e) {
    return e.map((e)=>({
            ...e,
            items: [
                ...e.items
            ]
        }));
}
function moveMenuItem(e, t, n, r) {
    let i = menu_layout_o(e), l = i.find((e)=>e.id === n);
    if (!l || r === t) return i;
    for (let e of i)e.items = e.items.filter((e)=>e !== t);
    let u = r ? l.items.indexOf(r) : -1;
    return u >= 0 ? l.items.splice(u, 0, t) : l.items.push(t), i;
}
function moveMenuCategory(e, t, n, r = "before") {
    let i = menu_layout_o(e), l = i.findIndex((e)=>e.id === t);
    if (l < 0 || t === n || !i.some((e)=>e.id === n)) return i;
    let [u] = i.splice(l, 1), a = i.findIndex((e)=>e.id === n);
    return i.splice("after" === r ? a + 1 : a, 0, u), i;
}
function menu_layout_u(e, t) {
    let n = e[t];
    return new Set(e.slice(t + 1).filter((e)=>e.originalPrimaryPath === n.originalPrimaryPath).map((e)=>e.path));
}
function canRestoreMenuItem(e, t, n) {
    let r = t.findIndex((e)=>e.path === n);
    if (r < 0) return !1;
    let i = primaryCategoryId(t[r].originalPrimaryPath), l = e.find((e)=>e.id === i);
    if (!l) return !0;
    let o = 0, a = -1;
    for (let t of e)for(let e = 0; e < t.items.length; e += 1)t.items[e] === n && (o += 1, t.id === i && (a = e));
    if (1 !== o || a < 0) return !0;
    let s = menu_layout_u(t, r), f = l.items.findIndex((e)=>s.has(e));
    return (f < 0 ? l.items.length - 1 : f > a ? f - 1 : f) !== a;
}
function restoreMenuItemToOriginalPosition(e, t, n) {
    let r = t.findIndex((e)=>e.path === n);
    if (r < 0) return menu_layout_o(e);
    let i = t[r], l = primaryCategoryId(i.originalPrimaryPath), a = e.some((e)=>e.id === l) ? e : [
        ...e,
        {
            id: l,
            title: i.originalPrimaryTitle,
            items: []
        }
    ], s = menu_layout_u(t, r), f = a.find((e)=>e.id === l);
    return moveMenuItem(a, n, l, f?.items.find((e)=>s.has(e)));
}
function menu_layout_a(e, t) {
    if ("string" != typeof e || e !== e.trim()) return !1;
    let n = e.split("/");
    return n.length === t && n.every(Boolean);
}
function menu_layout_s(e) {
    return "number" == typeof e ? `custom:${e}` : `primary:${e}`;
}
function menu_layout_f(e, t) {
    return Number.isInteger(e) && e >= 0 && e < t || menu_layout_a(e, 2) ? e : null;
}
function menu_layout_d(e, t) {
    let n = e[t];
    return void 0 === n ? [] : Array.isArray(n) ? n : null;
}
function parseMenuLayout(e) {
    let n;
    if ("string" != typeof e || "" === e.trim()) return null;
    try {
        n = JSON.parse(e);
    } catch  {
        return null;
    }
    if (!n || "object" != typeof n || Array.isArray(n)) return null;
    let r = n;
    if (1 !== r.version || Object.keys(r).some((e)=>!menu_layout_t.has(e))) return null;
    let i = menu_layout_d(r, "custom"), l = menu_layout_d(r, "titles"), o = menu_layout_d(r, "categoryMoves"), u = menu_layout_d(r, "itemMoves"), m = menu_layout_d(r, "hiddenCategories"), p = menu_layout_d(r, "hiddenItems");
    if (!i || !l || !o || !u || !m || !p) return null;
    let h = [], g = new Set();
    for (let e of i){
        if ("string" != typeof e) return null;
        let t = e.trim(), n = t.toLocaleLowerCase();
        if (!t || g.has(n)) return null;
        g.add(n), h.push(t);
    }
    let c = [], y = new Set();
    for (let e of l){
        if (!Array.isArray(e) || 2 !== e.length || !menu_layout_a(e[0], 2) || "string" != typeof e[1]) return null;
        let t = e[1].trim();
        if (!t || y.has(e[0])) return null;
        y.add(e[0]), c.push([
            e[0],
            t
        ]);
    }
    let M = [], v = new Set();
    for (let e of o){
        if (!Array.isArray(e) || 2 !== e.length) return null;
        let t = menu_layout_f(e[0], h.length), n = null === e[1] ? null : menu_layout_f(e[1], h.length);
        if (null === t || null !== e[1] && null === n) return null;
        let r = menu_layout_s(t);
        if (v.has(r) || null !== n && r === menu_layout_s(n)) return null;
        v.add(r), M.push([
            t,
            n
        ]);
    }
    let I = [], w = new Set();
    for (let e of u){
        if (!Array.isArray(e) || 3 !== e.length || !menu_layout_a(e[0], 3)) return null;
        let t = menu_layout_f(e[1], h.length), n = null === e[2] ? null : menu_layout_a(e[2], 3) ? e[2] : null;
        if (null === t || null !== e[2] && null === n || w.has(e[0]) || n === e[0]) return null;
        w.add(e[0]), I.push([
            e[0],
            t,
            n
        ]);
    }
    let C = [], x = new Set();
    for (let e of m){
        let t = menu_layout_f(e, h.length);
        if (null === t || x.has(menu_layout_s(t))) return null;
        x.add(menu_layout_s(t)), C.push(t);
    }
    let S = [], P = new Set();
    for (let e of p){
        if (!menu_layout_a(e, 3) || P.has(e)) return null;
        P.add(e), S.push(e);
    }
    return {
        version: 1,
        custom: h,
        titles: c,
        categoryMoves: M,
        itemMoves: I,
        hiddenCategories: C,
        hiddenItems: S
    };
}
function menu_layout_m() {
    return {
        titles: [],
        categoryMoves: [],
        itemMoves: []
    };
}
function menu_layout_p(e, t) {
    return "number" == typeof e ? t[e] ?? null : primaryCategoryId(e);
}
function resolveMenuLayout(e, t) {
    let n = menu_layout_i(e), r = menu_layout_l(n), u = new Set(), a = new Set(), s = menu_layout_m();
    if (!t) return {
        categories: r,
        hiddenCategoryIds: u,
        hiddenItemPaths: a,
        pending: s,
        configured: !1
    };
    let f = t.custom.map((e, t)=>{
        let n = `custom:${t}`;
        return r.push({
            id: n,
            title: e,
            items: []
        }), n;
    }), d = new Set(n.items.map((e)=>e.path)), h = f.length > 0;
    for (let [e, n] of t.titles){
        let t = primaryCategoryId(e), i = r.find((e)=>e.id === t);
        i ? (i.title = n, h = !0) : s.titles.push([
            t,
            n
        ]);
    }
    for (let [e, n] of t.categoryMoves){
        let t = menu_layout_p(e, f), i = null === n ? null : menu_layout_p(n, f), l = null !== t && r.some((e)=>e.id === t), u = null === i || r.some((e)=>e.id === i);
        t && l && u ? (r = function(e, t, n) {
            if (n) return moveMenuCategory(e, t, n);
            let r = menu_layout_o(e), i = r.findIndex((e)=>e.id === t);
            if (i < 0) return r;
            let [l] = r.splice(i, 1);
            return r.push(l), r;
        }(r, t, i), h = !0) : t && s.categoryMoves.push([
            t,
            i
        ]);
    }
    for (let [e, n, i] of t.itemMoves){
        let t = menu_layout_p(n, f), l = t ? r.find((e)=>e.id === t) : void 0, o = null === i || !!l?.items.includes(i);
        d.has(e) && t && l && o ? (r = moveMenuItem(r, e, t, i ?? void 0), h = !0) : t && s.itemMoves.push([
            e,
            t,
            i
        ]);
    }
    for (let e of t.hiddenCategories){
        let t = menu_layout_p(e, f);
        t && (u.add(t), r.some((e)=>e.id === t) && (h = !0));
    }
    for (let e of t.hiddenItems)a.add(e), d.has(e) && (h = !0);
    return {
        categories: r,
        hiddenCategoryIds: u,
        hiddenItemPaths: a,
        pending: s,
        configured: h
    };
}
function menu_layout_h(e, t) {
    let n = new Map(t.map((e, t)=>[
            e,
            t
        ])), r = e.flatMap((e)=>{
        let t = n.get(e);
        return void 0 === t ? [] : [
            {
                value: e,
                index: t
            }
        ];
    }), i = [], l = Array(r.length).fill(-1);
    for(let e = 0; e < r.length; e += 1){
        let t = 0, n = i.length;
        for(; t < n;){
            let l = t + n >> 1;
            r[i[l]].index < r[e].index ? t = l + 1 : n = l;
        }
        t > 0 && (l[e] = i[t - 1]), i[t] = e;
    }
    let o = new Set();
    for(let e = i.at(-1) ?? -1; e >= 0; e = l[e])o.add(r[e].value);
    return o;
}
function menu_layout_g(e, t) {
    let n = menu_layout_r(e);
    return n || (t.get(e) ?? null);
}
function menu_layout_c(e, t, n) {
    let r = n.get(e), i = n.get(t);
    return void 0 !== r && void 0 !== i ? r - i : void 0 !== r ? -1 : void 0 !== i ? 1 : e.localeCompare(t);
}
function serializeMenuLayout(e, t, n, o, u = menu_layout_m()) {
    let a = menu_layout_i(e), s = menu_layout_l(a), f = new Map(s.map((e)=>[
            e.id,
            e
        ])), d = t.filter((e)=>!f.has(e.id)), p = new Map(d.map((e, t)=>[
            e.id,
            t
        ])), y = d.map((e)=>e.title.trim()), M = [], v = new Set();
    for (let e of t){
        let t = f.get(e.id), n = e.title.trim();
        if (!t || n === t.title) continue;
        let i = menu_layout_r(e.id);
        i && (M.push([
            i,
            n
        ]), v.add(e.id));
    }
    for (let [e, t] of u.titles){
        if (v.has(e)) continue;
        let n = menu_layout_r(e);
        n && M.push([
            n,
            t
        ]);
    }
    let I = [
        ...s.map((e)=>e.id),
        ...d.map((e)=>e.id)
    ], w = t.map((e)=>e.id), C = [], x = new Set();
    for (let [e, t] of function(e, t) {
        let n = menu_layout_h(e, t), r = [];
        for(let e = t.length - 1; e >= 0; e -= 1)n.has(t[e]) || r.push([
            t[e],
            t[e + 1] ?? null
        ]);
        return r;
    }(I, w)){
        let n = menu_layout_g(e, p), r = null === t ? null : menu_layout_g(t, p);
        null !== n && (null === t || null !== r) && (C.push([
            n,
            r
        ]), x.add(e));
    }
    for (let [e, t] of u.categoryMoves){
        if (x.has(e)) continue;
        let n = menu_layout_g(e, p), r = null === t ? null : menu_layout_g(t, p);
        null !== n && (null === t || null !== r) && C.push([
            n,
            r
        ]);
    }
    let S = [], P = new Set();
    for (let e of t){
        let t = menu_layout_g(e.id, p);
        if (null === t) continue;
        let n = menu_layout_h(f.get(e.id)?.items ?? [], e.items);
        for(let r = e.items.length - 1; r >= 0; r -= 1){
            let i = e.items[r];
            n.has(i) || (S.push([
                i,
                t,
                e.items[r + 1] ?? null
            ]), P.add(i));
        }
    }
    for (let [e, t, n] of u.itemMoves){
        if (P.has(e)) continue;
        let r = menu_layout_g(t, p);
        null !== r && S.push([
            e,
            r,
            n
        ]);
    }
    let A = new Map(t.map((e, t)=>[
            e.id,
            t
        ])), b = [
        ...n
    ].sort((e, t)=>menu_layout_c(e, t, A)).flatMap((e)=>{
        let t = menu_layout_g(e, p);
        return null === t ? [] : [
            t
        ];
    }), $ = new Map(a.items.map((e, t)=>[
            e.path,
            t
        ])), L = [
        ...o
    ].sort((e, t)=>menu_layout_c(e, t, $)), O = {
        version: 1
    };
    return y.length > 0 && (O.custom = y), M.length > 0 && (O.titles = M), C.length > 0 && (O.categoryMoves = C), S.length > 0 && (O.itemMoves = S), b.length > 0 && (O.hiddenCategories = b), L.length > 0 && (O.hiddenItems = L), 1 === Object.keys(O).length ? "" : JSON.stringify(O);
}
function buildMenuPresentation(e, t) {
    let n = menu_layout_i(e), l = resolveMenuLayout(e, parseMenuLayout(t)), o = new Map(n.items.map((e)=>[
            e.path,
            e
        ])), u = new Map(n.primaries.map((e)=>[
            primaryCategoryId(e.path),
            e
        ])), a = new Set(l.hiddenItemPaths);
    for (let e of l.hiddenCategoryIds){
        let t = menu_layout_r(e);
        t && a.add(t);
        let n = l.categories.find((t)=>t.id === e);
        if (n) for (let e of n.items)a.add(e);
    }
    return {
        categories: l.categories.map((e)=>({
                id: e.id,
                title: e.title,
                primary: u.get(e.id) ?? null,
                items: e.items.flatMap((e)=>{
                    let t = o.get(e);
                    return t ? [
                        t
                    ] : [];
                })
            })),
        hiddenCategoryIds: l.hiddenCategoryIds,
        hiddenPaths: a,
        configured: l.configured
    };
}

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/menu.tsx

let menu_a = L.form;

let menu_m = "application/x-fluent-menu-category", menu_p = "application/x-fluent-menu-item";
function menu_f(e, t) {
    let a = t.getBoundingClientRect();
    return e.clientY < a.top + a.height / 2 ? "before" : "after";
}
let menu_v = 0;
function menu_h(e) {
    return e.trim().toLocaleLowerCase();
}
function menu_y(e) {
    let t = new Map(), a = new Map();
    for (let i of e){
        let e = i.title.trim(), n = menu_h(e);
        if (!e) {
            t.set(i.id, _("Primary menu titles cannot be empty."));
            continue;
        }
        let r = a.get(n);
        r ? (t.set(r, _("Primary menu titles must be unique.")), t.set(i.id, _("Primary menu titles must be unique."))) : a.set(n, i.id);
    }
    return t;
}
function registerMenuTab(b, E) {
    var M;
    let D, I, w, T;
    b.tab("menu", _("Menu"));
    let P = b.taboption("menu", (M = E, I = new Map((D = discoverMenuItems(M)).map((e)=>[
            e.path,
            e
        ])), w = new Map(buildDefaultMenuCategories(M).map((e)=>[
            e.id,
            e
        ])), T = new Map(), menu_a.Value.extend({
        renderWidget (a, r, b) {
            let E = "string" == typeof b || Array.isArray(b) ? b : null, P = "string" == typeof b ? b : "", C = function(e, t) {
                let a = parseMenuLayout(t);
                if (!a) return {
                    categories: buildDefaultMenuCategories(e),
                    hiddenCategoryIds: new Set(),
                    hiddenItemPaths: new Set(),
                    pending: {
                        titles: [],
                        categoryMoves: [],
                        itemMoves: []
                    }
                };
                let n = resolveMenuLayout(e, a);
                return {
                    categories: n.categories,
                    hiddenCategoryIds: n.hiddenCategoryIds,
                    hiddenItemPaths: n.hiddenItemPaths,
                    pending: n.pending
                };
            }(M, E), k = new Set(), x = "" === P ? null : parseMenuLayout(P), S = "" !== P && !x, R = jsx("input", {
                type: "hidden",
                id: this.cbid(a),
                value: P
            }), A = jsx("div", {
                class: "fluent-menu-editor__categories"
            }), N = new Map(), U = null, $ = "before", j = jsx("div", {
                class: "fluent-menu-editor__validation",
                role: "alert"
            }), q = jsx("div", {
                class: "fluent-menu-editor__notice",
                hidden: !S,
                children: _('The stored menu layout is invalid. Choose "Restore defaults" or make an edit before saving.')
            });
            T.set(a, R);
            let z = ()=>{
                let e = menu_y(C.categories);
                for (let [t, a] of N){
                    let i = e.get(t) ?? "";
                    a.card.classList.toggle("is-invalid", !!i), a.error && (a.error.textContent = i);
                }
                j.textContent = e.size > 0 ? _("Fix primary menu title errors before saving.") : "";
            }, B = (e = serializeMenuLayout(M, C.categories, C.hiddenCategoryIds, C.hiddenItemPaths, C.pending))=>{
                R.value = e, q.hidden = !0, z(), R.dispatchEvent(new Event("change", {
                    bubbles: !0
                }));
            }, F = ()=>{
                U?.classList.remove("is-drop-before", "is-drop-after"), U = null;
            }, O = (e, t)=>{
                (U !== e || $ !== t) && F(), U = e, $ = t, e.classList.toggle("is-drop-before", "before" === t), e.classList.toggle("is-drop-after", "after" === t);
            }, V = (e, t, a)=>{
                I.has(e) && C.categories.some((e)=>e.id === t) && (C.pending.itemMoves = C.pending.itemMoves.filter(([t])=>t !== e), C.categories = moveMenuItem(C.categories, e, t, a), k.add(t), B(), W());
            };
            function W() {
                N.clear(), dom.content(A, C.categories.map((a)=>((a)=>{
                        let i = document.createElement("details");
                        i.className = `fluent-menu-editor__category${C.hiddenCategoryIds.has(a.id) ? " is-hidden" : ""}`, i.dataset.categoryId = a.id, i.open = k.has(a.id);
                        let r = document.createElement("summary");
                        r.className = "fluent-menu-editor__category-header";
                        let s = jsx("div", {
                            class: "fluent-menu-editor__items",
                            "data-category-id": a.id
                        }), l = jsx("span", {
                            class: "fluent-menu-editor__category-count",
                            title: _("%d second-level menus").format(a.items.length),
                            children: a.items.length
                        }), u = jsx("div", {
                            class: "fluent-menu-editor__category-error",
                            role: "alert"
                        }), g = !1, v = ()=>{
                            if (g) return;
                            let i = a.items.flatMap((i)=>{
                                let r = ((a, i)=>{
                                    let r = I.get(a), d = C.categories.find((e)=>e.id === i);
                                    if (!r || !d) return null;
                                    let s = jsx("div", {
                                        class: `fluent-menu-editor__item${C.hiddenItemPaths.has(a) ? " is-hidden" : ""}`,
                                        "data-item-path": a
                                    }), l = jsx("span", {
                                        class: "fluent-menu-editor__drag-handle",
                                        title: _("Drag to move second-level menu"),
                                        children: "\u22EE\u22EE"
                                    }), u = jsx("input", {
                                        type: "checkbox",
                                        checked: !C.hiddenItemPaths.has(a),
                                        "aria-label": _("Show %s in the menu").format(r.title)
                                    });
                                    l.draggable = !0, l.addEventListener("dragstart", (e)=>{
                                        e.dataTransfer?.setData(menu_p, a), e.dataTransfer && (e.dataTransfer.effectAllowed = "move"), s.classList.add("is-dragging");
                                    }), l.addEventListener("dragend", ()=>{
                                        s.classList.remove("is-dragging"), F();
                                    }), u.addEventListener("change", ()=>{
                                        u.checked ? C.hiddenItemPaths.delete(a) : C.hiddenItemPaths.add(a), s.classList.toggle("is-hidden", !u.checked), B();
                                    }), s.addEventListener("dragover", (e)=>{
                                        e.dataTransfer?.types.includes(menu_p) && (e.preventDefault(), e.stopPropagation(), O(s, menu_f(e, s)));
                                    }), s.addEventListener("dragleave", (e)=>{
                                        s.contains(e.relatedTarget) || U !== s || F();
                                    }), s.addEventListener("drop", (e)=>{
                                        let t = e.dataTransfer?.getData(menu_p);
                                        if (!t) return;
                                        e.preventDefault(), e.stopPropagation();
                                        let n = U === s ? $ : menu_f(e, s), r = d.items.indexOf(a), l = "before" === n ? a : d.items[r + 1];
                                        F(), V(t, i, l);
                                    });
                                    let g = jsxs("span", {
                                        class: "fluent-menu-editor__item-label",
                                        children: [
                                            jsx("strong", {
                                                children: r.title
                                            }),
                                            jsx("small", {
                                                children: r.path
                                            })
                                        ]
                                    });
                                    if (s.append(l, u, g), canRestoreMenuItem(C.categories, D, a)) {
                                        let t = _("Restore %s to its original menu position").format(r.title), i = jsx("button", {
                                            class: "fluent-menu-editor__item-reset",
                                            type: "button",
                                            "aria-label": t,
                                            title: t
                                        });
                                        i.addEventListener("click", ()=>{
                                            let e;
                                            (e = I.get(a)) && k.add(primaryCategoryId(e.originalPrimaryPath)), C.pending.itemMoves = C.pending.itemMoves.filter(([e])=>e !== a), C.categories = restoreMenuItemToOriginalPosition(C.categories, D, a), B(), W();
                                        }), s.append(i);
                                    }
                                    return s;
                                })(i, a.id);
                                return r ? [
                                    r
                                ] : [];
                            });
                            i.length > 0 ? s.append(...i) : s.appendChild(jsx("div", {
                                class: "fluent-menu-editor__empty",
                                children: _("Drop second-level menus here")
                            })), g = !0;
                        };
                        i.addEventListener("toggle", ()=>{
                            i.open ? (k.add(a.id), v()) : k.delete(a.id);
                        }), s.addEventListener("dragover", (e)=>{
                            e.dataTransfer?.types.includes(menu_p) && (e.preventDefault(), s.classList.add("is-drag-over"));
                        }), s.addEventListener("dragleave", (e)=>{
                            s.contains(e.relatedTarget) || s.classList.remove("is-drag-over");
                        }), s.addEventListener("drop", (e)=>{
                            let t = e.dataTransfer?.getData(menu_p);
                            t && (e.preventDefault(), e.stopPropagation(), s.classList.remove("is-drag-over"), V(t, a.id));
                        }), i.open && v();
                        let h = C.categories.length > 1, y = w.get(a.id), b = jsx("input", {
                            type: "checkbox",
                            checked: !C.hiddenCategoryIds.has(a.id),
                            "aria-label": _("Show %s in the menu").format(a.title)
                        }), E = jsx("input", {
                            class: "fluent-menu-editor__category-title",
                            type: "text",
                            value: a.title,
                            "aria-label": _("Primary menu title")
                        });
                        b.addEventListener("change", ()=>{
                            b.checked ? C.hiddenCategoryIds.delete(a.id) : C.hiddenCategoryIds.add(a.id), i.classList.toggle("is-hidden", !b.checked), B();
                        });
                        let M = null;
                        if (y) {
                            let t = _("Restore %s to its original menu name").format(y.title), i = jsx("button", {
                                class: "fluent-menu-editor__category-reset",
                                type: "button",
                                "aria-label": t,
                                title: t
                            });
                            i.hidden = a.title.trim() === y.title, i.addEventListener("click", ()=>{
                                a.title = y.title, E.value = y.title, i.hidden = !0, B();
                            }), M = i;
                        }
                        if (E.addEventListener("input", ()=>{
                            a.title = E.value, M && y && (M.hidden = E.value.trim() === y.title), B();
                        }), E.addEventListener("blur", ()=>{
                            a.title = E.value.trim(), E.value = a.title, M && y && (M.hidden = a.title === y.title), B();
                        }), h) {
                            let t = jsx("span", {
                                class: "fluent-menu-editor__drag-handle",
                                title: _("Drag to reorder primary menu"),
                                children: "\u22EE\u22EE"
                            });
                            t.draggable = !0, t.addEventListener("dragstart", (e)=>{
                                e.dataTransfer?.setData(menu_m, a.id), e.dataTransfer && (e.dataTransfer.effectAllowed = "move"), i.classList.add("is-dragging");
                            }), t.addEventListener("dragend", ()=>{
                                i.classList.remove("is-dragging"), F();
                            }), r.append(t);
                        }
                        if (r.append(b, E, l), M && r.append(M), !y) {
                            let t = jsx("button", {
                                class: "fluent-menu-editor__category-delete",
                                type: "button",
                                "aria-label": _("Delete primary menu"),
                                title: _("Delete primary menu")
                            });
                            t.addEventListener("click", ()=>{
                                let e = [
                                    ...a.items
                                ];
                                for (let t of (C.categories = C.categories.filter((e)=>e.id !== a.id), C.hiddenCategoryIds.delete(a.id), C.pending.categoryMoves = C.pending.categoryMoves.filter(([e, t])=>e !== a.id && t !== a.id), C.pending.itemMoves = C.pending.itemMoves.filter(([, e])=>e !== a.id), k.delete(a.id), e))C.pending.itemMoves = C.pending.itemMoves.filter(([e])=>e !== t), C.categories = restoreMenuItemToOriginalPosition(C.categories, D, t);
                                B(), W();
                            }), r.append(t);
                        }
                        i.addEventListener("dragover", (e)=>{
                            let t = e.dataTransfer?.types.includes(menu_p);
                            if (h && e.dataTransfer?.types.includes(menu_m)) {
                                e.preventDefault(), O(i, menu_f(e, i));
                                return;
                            }
                            !t || s.contains(e.target) || (e.preventDefault(), O(i, "after"));
                        }), i.addEventListener("dragleave", (e)=>{
                            i.contains(e.relatedTarget) || U === i && F();
                        }), i.addEventListener("drop", (e)=>{
                            let t = e.dataTransfer?.getData(menu_p);
                            if (t) {
                                e.preventDefault(), F(), V(t, a.id);
                                return;
                            }
                            let n = e.dataTransfer?.getData(menu_m);
                            if (!h || !n || n === a.id) return;
                            e.preventDefault();
                            let r = U === i ? $ : menu_f(e, i);
                            F(), C.pending.categoryMoves = C.pending.categoryMoves.filter(([e])=>e !== n), C.categories = moveMenuCategory(C.categories, n, a.id, r), B(), W();
                        }), i.append(r), u && i.append(u), i.append(s);
                        let T = {
                            card: i
                        };
                        return u && (T.error = u), N.set(a.id, T), i;
                    })(a))), z();
            }
            let Y = jsx("button", {
                class: "btn cbi-button cbi-button-add",
                type: "button",
                children: _("Add primary menu")
            }), G = jsx("button", {
                class: "btn cbi-button cbi-button-reset",
                type: "button",
                children: _("Restore defaults")
            });
            return Y.addEventListener("click", ()=>{
                let e = _("New primary menu"), t = new Set(C.categories.map((e)=>menu_h(e.title))), a = e, i = 2;
                for(; t.has(menu_h(a));)a = _("New primary menu %d").format(i), i += 1;
                let n = "u" > typeof crypto && "function" == typeof crypto.randomUUID ? crypto.randomUUID() : (menu_v += 1, `category-${Date.now()}-${menu_v}`);
                C.categories.push({
                    id: n,
                    title: a,
                    items: []
                }), k.add(n), B(), W();
            }), G.addEventListener("click", ()=>{
                C = {
                    categories: buildDefaultMenuCategories(M),
                    hiddenCategoryIds: new Set(),
                    hiddenItemPaths: new Set(),
                    pending: {
                        titles: [],
                        categoryMoves: [],
                        itemMoves: []
                    }
                }, k.clear(), B(""), W();
            }), W(), jsxs("div", {
                class: "fluent-menu-editor",
                children: [
                    R,
                    q,
                    jsx("div", {
                        class: "fluent-menu-editor__actions",
                        children: [
                            Y,
                            G
                        ]
                    }),
                    j,
                    A
                ]
            });
        },
        formvalue: (e)=>T.get(e)?.value ?? "",
        validate: (e, t)=>(function(e, t) {
                if ("" === t || null == t) return !0;
                if ("string" != typeof t) return _("The stored menu layout is invalid. Restore defaults or edit the layout before saving.");
                let a = parseMenuLayout(t);
                return a ? menu_y(resolveMenuLayout(e, a).categories).values().next().value ?? !0 : _("The stored menu layout is invalid. Restore defaults or edit the layout before saving.");
            })(M, t)
    })), "menu_layout");
    P.optional = !0, P.rmempty = !0;
}

;// CONCATENATED MODULE: ./web/resources/view/fluent-config.tsx
let fluent_config_e = L.form, fluent_config_o = L.uci;







class fluent_config_m extends L.view {
    load() {
        return Promise.all([
            fluent_config_o.load("fluent"),
            L.ui.menu.load()
        ]);
    }
    render(o) {
        let [, m] = o, s = new fluent_config_e.Map("fluent", _("Fluent theme settings"), _("Configure color mode, accent colors, layout sizing, animation behavior, login-page appearance, and advanced CSS overrides for luci-theme-fluent.")), u = s.section(fluent_config_e.TypedSection, "global", _("Theme settings"));
        return u.addremove = !1, u.anonymous = !0, registerGeneralTab(u), registerMenuTab(u, m), registerColorsTab(u), registerAnimationTab(u), registerLoginTab(u), registerAdvancedTab(u), registerAboutTab(u), s.render();
    }
}
const main = fluent_config_m;


return main;